import { Navbar } from "@/components/navbar";
import { Button } from "@/components/ui/button";
import { Mic, Brain, Users, Zap } from "lucide-react";

export default function Home() {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />

      {/* Hero Section */}
      <main className="container mx-auto px-4 py-16">
        <div className="text-center space-y-8">
          <h1 className="text-4xl md:text-6xl font-bold tracking-tight">
            Master Your
            <span className="text-primary block">Interview Skills</span>
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            AI-powered mock interviews with voice interaction to simulate real interview experiences. 
            Practice with confidence using advanced AI technology.
          </p>
          
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button size="lg" className="gap-2">
              <Mic className="h-4 w-4" />
              Start Interview
            </Button>
            <Button variant="outline" size="lg" className="gap-2">
              <Users className="h-4 w-4" />
              Learn More
            </Button>
          </div>
        </div>

        {/* Features Grid */}
        <div className="mt-24 grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="text-center space-y-4">
            <div className="mx-auto w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center">
              <Brain className="h-6 w-6 text-primary" />
            </div>
            <h3 className="text-xl font-semibold">AI-Powered Questions</h3>
            <p className="text-muted-foreground">
              Dynamic interview questions generated by Google Gemini AI tailored to your experience level and technology stack.
            </p>
          </div>
          
          <div className="text-center space-y-4">
            <div className="mx-auto w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center">
              <Mic className="h-6 w-6 text-primary" />
            </div>
            <h3 className="text-xl font-semibold">Voice Interaction</h3>
            <p className="text-muted-foreground">
              Natural voice conversations using VY AI for speech recognition and synthesis, just like real interviews.
            </p>
          </div>
          
          <div className="text-center space-y-4">
            <div className="mx-auto w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center">
              <Zap className="h-6 w-6 text-primary" />
            </div>
            <h3 className="text-xl font-semibold">Instant Feedback</h3>
            <p className="text-muted-foreground">
              Get detailed AI-generated feedback on your technical knowledge, communication, and problem-solving skills.
            </p>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border/40 mt-24">
        <div className="container mx-auto px-4 py-8 text-center text-muted-foreground">
          <p>© 2024 PushGrade Interview System. Built with Next.js, Tailwind CSS, and AI technology.</p>
        </div>
      </footer>
    </div>
  );
}
